"""Human-readable outputs. All are generated from the same Record, so they always match the JSON."""
import re

# Make text safe inside a Markdown table cell.
def _cell(text):
    return str(text).replace("|", "\\|").replace("\r", " ").replace("\n", " ").strip()

# Builds the evidence line for a decision, proposal or task. It returns "exact words said" (timestamp),
# or an empty string if there is no evidence
def _quote(item):
    if not item.evidence:
        return ""
    ts = f" ({item.timestamp})" if item.timestamp else ""
    return f'"{item.evidence.strip()}"{ts}'

# Builds the Summary and Minutes sections.
def minutes_md(r):
    lines = ["## Summary", r.summary, "", "## Minutes"]
    if not r.minutes:
        lines.append("_No separate discussion topics were identified._")
    for s in r.minutes:
        lines.append(f"### {s.topic}")
        lines += [f"- {p}" for p in s.points]
        lines.append("")
    return "\n".join(lines).strip()

# Builds a numbered list of agreed decisions, each followed by its supporting quote as a blockquote (>).
def decisions_md(r):
    if not r.decisions:
        return "_No decisions were clearly agreed in this meeting._"
    out = []
    for i, d in enumerate(r.decisions, 1):
        out.append(f"{i}. {d.decision}")
        q = _quote(d)
        if q:
            out.append(f"   > {q}")
    return "\n".join(out)

# Same layout as decisions, but for suggestions that were raised and not agreed.
def proposals_md(r):
    if not r.proposals:
        return "_No proposals were raised without being agreed._"
    out = ["_Suggestions that were raised but not agreed. They are NOT decisions._", ""]
    for i, p in enumerate(r.proposals, 1):
        out.append(f"{i}. {p.proposal}")
        q = _quote(p)
        if q:
            out.append(f"   > {q}")
    return "\n".join(out)

# Builds the action items as a Markdown table with the columns #, Task, Owner, Deadline, Status and Evidence
def tasks_md(r):
    if not r.tasks:
        return "_No action items were stated in this meeting._"
    rows = ["| # | Task | Owner | Deadline | Status | Evidence (time) |",
            "|---|------|-------|----------|--------|-----------------|"]
    for i, t in enumerate(r.tasks, 1):
        rows.append(f"| {i} | {_cell(t.description)} | {_cell(t.owner)} | {_cell(t.deadline)} | "
                    f"{t.status} | {_cell(_quote(t))} |")
    rows += ["", "_Status: `assigned` = someone was asked to do it or took it on; "
                 "`suggested` = raised but nobody committed. Owner/deadline show `unspecified` when not said._"]
    return "\n".join(rows)

# Combines everything above into one meeting_record.md: Minutes, Key Decisions, Proposals and Action Items.
def full_md(r, meta=None):
    parts = ["# Meeting Record", minutes_md(r), "## Key Decisions", decisions_md(r),
             "## Proposals (not agreed)", proposals_md(r), "## Action Items", tasks_md(r)]
    if meta:
        if meta.get("warnings"):
            parts += ["## Processing notes"] + ["\n".join(f"- {w}" for w in meta["warnings"])]
        parts += ["---", f"_Generated by: STT `{meta['stt_model']}`, refinement `{meta['llm1_model']}`, "
                         f"minutes `{meta['llm2_model']}` (profile: {meta['profile']})_"]
    return "\n\n".join(parts)

# Refined transcript as [(text, label)] pairs for gr.HighlightedText; corrected terms get the label 'corrected'.
# it is for gradio not files. 
def highlight_pairs(refined, corrections):
    by_line = {}
    for c in corrections:
        by_line.setdefault(c["line"], []).append(c["to"])
    pairs = []
    for seg in refined.segments:
        pairs.append((f"[{seg.ts}] ", None))
        targets = sorted(set(by_line.get(seg.id, [])), key=len, reverse=True)
        if targets:
            pattern = "(" + "|".join(re.escape(t) for t in targets) + ")"
            for piece in re.split(pattern, seg.text):
                if piece:
                    pairs.append((piece, "corrected" if piece in targets else None))
        else:
            pairs.append((seg.text, None))
        pairs.append(("\n", None))
    return pairs
